sudo: required
services:
    - docker

before_install:
    - docker build -t jablam13/react-test -f ./client/Dockerfile.dev ./client
    # - docker build -t jablam13/nodejs-test -f ./server/Dockerfile.dev ./server

script:
    # - docker run jablam13/react-test npm test -- --coverage
    - docker run -e CI=true jablam13/react-test npm test
    # - docker run -e CI=true jablam13/nodejs-test npm test

after_success:
    - docker build -t jablam13/multi-client ./client
    - docker build -t jablam13/multi-nginx ./nginx
    - docker build -t jablam13/multi-server ./server
    - docker build -t jablam13/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push jablam13/multi-client
    - docker push jablam13/multi-nginx
    - docker push jablam13/multi-server
    - docker push jablam13/multi-worker

